FORMAT: 1A

# docgen
API allows you to generate multiple docx documents using specified template and data

# Generation

For all following actions, API key specified in HTTP header is required.

## Template [/api/v1/template]
### Upload template [POST]

Creates new template. Returns its ID and MD5 checksum.

+ Request
    
    + Headers
        
            X-Auth: API key

+ Attributes
    + file (required, array) - POST file type

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)

        {
            "template_id": 10,
            "md5": "09f5f87a3bf63e32a8325b9202a5ed78"
        }
 
+ Response 401 (application/json)
        
        {
            "error": "API key is invalid."
        }

+ Response 500 (application/json)

        {
            "error_id": 1,
            "error": "File is too big."
        }

### Delete template [GET /api/v1/template/{template_id}]

Deletes template pernamently.

+ Request
    
    + Headers
    
            X-Auth: API key

+ Parameters
    + template_id (required, number) - template ID

+ Response 200 (application/json)
 
+ Response 401 (application/json)
        
        {
            "error": "API key is invalid."
        }

+ Response 404 (application/json)
        
        {
            "error": "Template ID is invalid."
        }



## Requests [/api/v1/request]
### Create request [POST]

Creates new request. Returns its ID.

+ Request
    
    + Headers
        
            X-Auth: API key

+ Attributes (object)
    + template_id (required, number) - ID of template to be used for generation
    + type (required, string) - Result type, pdf or docx
    + data (required, object) - Template data
    + response_url (optional, string) - URL that will be called, when request is completed

+ Request (application/json)
        
        {
            "template_id": 18,
            "data": {
                "sender": "Kumos me, Apur Susu 12, Segal",
                "receiver": "Kule Huhu, Alamar 26, Gugu, Mongo",
                "items": [
                    {
                        "name": "Item 1",
                        "count": 1,
                        "price": 10
                    },
                    {
                        "name": "Item 2",
                        "count": 5,
                        "price": 20
                    }
                ]
            }
        }

+ Response 200 (application/json)

        {
            "request_id": 10
        }
        
+ Response 401 (application/json)

        {
            "error": "API key is invalid.",
        }

+ Response 404 (application/json)

        {
            "error": "Invalid template id.",
        }
        
+ Response 417 (application/json)

        {
            "error": "No data specified.",
        }

## Informations [/api/v1/request/{request_id}]

Returns details about request including. When request is completed, it will include link to download generated documents.

+ Parameters
    + request_id (number, required) - ID of request

### Request details [GET]

+ Request
    
    + Headers
        
            X-Auth: API key

+ Response 200 (application/json)

    + Body
    
            {
                "id": 10,
                "template_id": 128,
                "completed": true,
                "download_url": "http://..../request-10.zip"
            }

+ Response 401 (application/json)

        {
            "error": "API key is invalid.",
        }

+ Response 404 (application/json)

        {
            "error": "Invalid template id.",
        }
